# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/envelopes/unknown6_response.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from pogoprotos.data.player import currency_pb2 as pogoprotos_dot_data_dot_player_dot_currency__pb2
from pogoprotos.inventory.item import item_data_pb2 as pogoprotos_dot_inventory_dot_item_dot_item__data__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/envelopes/unknown6_response.proto',
  package='pogoprotos.networking.envelopes',
  syntax='proto3',
  serialized_pb=_b('\n7pogoprotos/networking/envelopes/unknown6_response.proto\x12\x1fpogoprotos.networking.envelopes\x1a%pogoprotos/data/player/currency.proto\x1a)pogoprotos/inventory/item/item_data.proto\"\xa6\x05\n\x10Unknown6Response\x12\x15\n\rresponse_type\x18\x01 \x01(\x05\x12L\n\x08unknown2\x18\x02 \x01(\x0b\x32:.pogoprotos.networking.envelopes.Unknown6Response.Unknown2\x1a\xac\x04\n\x08Unknown2\x12\x10\n\x08unknown1\x18\x01 \x01(\x04\x12S\n\x05items\x18\x02 \x03(\x0b\x32\x44.pogoprotos.networking.envelopes.Unknown6Response.Unknown2.StoreItem\x12;\n\x11player_currencies\x18\x03 \x03(\x0b\x32 .pogoprotos.data.player.Currency\x12\x10\n\x08unknown4\x18\x04 \x01(\t\x1a\xe9\x02\n\tStoreItem\x12\x0f\n\x07item_id\x18\x01 \x01(\t\x12\x0e\n\x06is_iap\x18\x02 \x01(\x08\x12\x39\n\x0f\x63urrency_to_buy\x18\x03 \x01(\x0b\x32 .pogoprotos.data.player.Currency\x12\x39\n\x0fyields_currency\x18\x04 \x01(\x0b\x32 .pogoprotos.data.player.Currency\x12\x38\n\x0byields_item\x18\x05 \x01(\x0b\x32#.pogoprotos.inventory.item.ItemData\x12V\n\x04tags\x18\x06 \x03(\x0b\x32H.pogoprotos.networking.envelopes.Unknown6Response.Unknown2.StoreItem.Tag\x12\x10\n\x08unknown7\x18\x07 \x01(\x05\x1a!\n\x03Tag\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\tb\x06proto3')
  ,
  dependencies=[pogoprotos_dot_data_dot_player_dot_currency__pb2.DESCRIPTOR,pogoprotos_dot_inventory_dot_item_dot_item__data__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_UNKNOWN6RESPONSE_UNKNOWN2_STOREITEM_TAG = _descriptor.Descriptor(
  name='Tag',
  full_name='pogoprotos.networking.envelopes.Unknown6Response.Unknown2.StoreItem.Tag',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='pogoprotos.networking.envelopes.Unknown6Response.Unknown2.StoreItem.Tag.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='pogoprotos.networking.envelopes.Unknown6Response.Unknown2.StoreItem.Tag.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=820,
  serialized_end=853,
)

_UNKNOWN6RESPONSE_UNKNOWN2_STOREITEM = _descriptor.Descriptor(
  name='StoreItem',
  full_name='pogoprotos.networking.envelopes.Unknown6Response.Unknown2.StoreItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='item_id', full_name='pogoprotos.networking.envelopes.Unknown6Response.Unknown2.StoreItem.item_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_iap', full_name='pogoprotos.networking.envelopes.Unknown6Response.Unknown2.StoreItem.is_iap', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='currency_to_buy', full_name='pogoprotos.networking.envelopes.Unknown6Response.Unknown2.StoreItem.currency_to_buy', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='yields_currency', full_name='pogoprotos.networking.envelopes.Unknown6Response.Unknown2.StoreItem.yields_currency', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='yields_item', full_name='pogoprotos.networking.envelopes.Unknown6Response.Unknown2.StoreItem.yields_item', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tags', full_name='pogoprotos.networking.envelopes.Unknown6Response.Unknown2.StoreItem.tags', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unknown7', full_name='pogoprotos.networking.envelopes.Unknown6Response.Unknown2.StoreItem.unknown7', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_UNKNOWN6RESPONSE_UNKNOWN2_STOREITEM_TAG, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=492,
  serialized_end=853,
)

_UNKNOWN6RESPONSE_UNKNOWN2 = _descriptor.Descriptor(
  name='Unknown2',
  full_name='pogoprotos.networking.envelopes.Unknown6Response.Unknown2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='unknown1', full_name='pogoprotos.networking.envelopes.Unknown6Response.Unknown2.unknown1', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='items', full_name='pogoprotos.networking.envelopes.Unknown6Response.Unknown2.items', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='player_currencies', full_name='pogoprotos.networking.envelopes.Unknown6Response.Unknown2.player_currencies', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unknown4', full_name='pogoprotos.networking.envelopes.Unknown6Response.Unknown2.unknown4', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_UNKNOWN6RESPONSE_UNKNOWN2_STOREITEM, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=297,
  serialized_end=853,
)

_UNKNOWN6RESPONSE = _descriptor.Descriptor(
  name='Unknown6Response',
  full_name='pogoprotos.networking.envelopes.Unknown6Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='response_type', full_name='pogoprotos.networking.envelopes.Unknown6Response.response_type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unknown2', full_name='pogoprotos.networking.envelopes.Unknown6Response.unknown2', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_UNKNOWN6RESPONSE_UNKNOWN2, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=175,
  serialized_end=853,
)

_UNKNOWN6RESPONSE_UNKNOWN2_STOREITEM_TAG.containing_type = _UNKNOWN6RESPONSE_UNKNOWN2_STOREITEM
_UNKNOWN6RESPONSE_UNKNOWN2_STOREITEM.fields_by_name['currency_to_buy'].message_type = pogoprotos_dot_data_dot_player_dot_currency__pb2._CURRENCY
_UNKNOWN6RESPONSE_UNKNOWN2_STOREITEM.fields_by_name['yields_currency'].message_type = pogoprotos_dot_data_dot_player_dot_currency__pb2._CURRENCY
_UNKNOWN6RESPONSE_UNKNOWN2_STOREITEM.fields_by_name['yields_item'].message_type = pogoprotos_dot_inventory_dot_item_dot_item__data__pb2._ITEMDATA
_UNKNOWN6RESPONSE_UNKNOWN2_STOREITEM.fields_by_name['tags'].message_type = _UNKNOWN6RESPONSE_UNKNOWN2_STOREITEM_TAG
_UNKNOWN6RESPONSE_UNKNOWN2_STOREITEM.containing_type = _UNKNOWN6RESPONSE_UNKNOWN2
_UNKNOWN6RESPONSE_UNKNOWN2.fields_by_name['items'].message_type = _UNKNOWN6RESPONSE_UNKNOWN2_STOREITEM
_UNKNOWN6RESPONSE_UNKNOWN2.fields_by_name['player_currencies'].message_type = pogoprotos_dot_data_dot_player_dot_currency__pb2._CURRENCY
_UNKNOWN6RESPONSE_UNKNOWN2.containing_type = _UNKNOWN6RESPONSE
_UNKNOWN6RESPONSE.fields_by_name['unknown2'].message_type = _UNKNOWN6RESPONSE_UNKNOWN2
DESCRIPTOR.message_types_by_name['Unknown6Response'] = _UNKNOWN6RESPONSE

Unknown6Response = _reflection.GeneratedProtocolMessageType('Unknown6Response', (_message.Message,), dict(

  Unknown2 = _reflection.GeneratedProtocolMessageType('Unknown2', (_message.Message,), dict(

    StoreItem = _reflection.GeneratedProtocolMessageType('StoreItem', (_message.Message,), dict(

      Tag = _reflection.GeneratedProtocolMessageType('Tag', (_message.Message,), dict(
        DESCRIPTOR = _UNKNOWN6RESPONSE_UNKNOWN2_STOREITEM_TAG,
        __module__ = 'pogoprotos.networking.envelopes.unknown6_response_pb2'
        # @@protoc_insertion_point(class_scope:pogoprotos.networking.envelopes.Unknown6Response.Unknown2.StoreItem.Tag)
        ))
      ,
      DESCRIPTOR = _UNKNOWN6RESPONSE_UNKNOWN2_STOREITEM,
      __module__ = 'pogoprotos.networking.envelopes.unknown6_response_pb2'
      # @@protoc_insertion_point(class_scope:pogoprotos.networking.envelopes.Unknown6Response.Unknown2.StoreItem)
      ))
    ,
    DESCRIPTOR = _UNKNOWN6RESPONSE_UNKNOWN2,
    __module__ = 'pogoprotos.networking.envelopes.unknown6_response_pb2'
    # @@protoc_insertion_point(class_scope:pogoprotos.networking.envelopes.Unknown6Response.Unknown2)
    ))
  ,
  DESCRIPTOR = _UNKNOWN6RESPONSE,
  __module__ = 'pogoprotos.networking.envelopes.unknown6_response_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.envelopes.Unknown6Response)
  ))
_sym_db.RegisterMessage(Unknown6Response)
_sym_db.RegisterMessage(Unknown6Response.Unknown2)
_sym_db.RegisterMessage(Unknown6Response.Unknown2.StoreItem)
_sym_db.RegisterMessage(Unknown6Response.Unknown2.StoreItem.Tag)


# @@protoc_insertion_point(module_scope)
