# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pogoprotos/networking/responses/add_fort_modifier_response.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pogoprotos/networking/responses/add_fort_modifier_response.proto',
  package='pogoprotos.networking.responses',
  syntax='proto3',
  serialized_pb=_b('\n@pogoprotos/networking/responses/add_fort_modifier_response.proto\x12\x1fpogoprotos.networking.responses\"\x19\n\x17\x41\x64\x64\x46ortModifierResponseb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ADDFORTMODIFIERRESPONSE = _descriptor.Descriptor(
  name='AddFortModifierResponse',
  full_name='pogoprotos.networking.responses.AddFortModifierResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=126,
)

DESCRIPTOR.message_types_by_name['AddFortModifierResponse'] = _ADDFORTMODIFIERRESPONSE

AddFortModifierResponse = _reflection.GeneratedProtocolMessageType('AddFortModifierResponse', (_message.Message,), dict(
  DESCRIPTOR = _ADDFORTMODIFIERRESPONSE,
  __module__ = 'pogoprotos.networking.responses.add_fort_modifier_response_pb2'
  # @@protoc_insertion_point(class_scope:pogoprotos.networking.responses.AddFortModifierResponse)
  ))
_sym_db.RegisterMessage(AddFortModifierResponse)


# @@protoc_insertion_point(module_scope)
